#!/usr/bin/env bash
# redirection /redirect_me
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 http://graceeffiong.tech/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
