#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.

apt-get update -y
apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
