#!/usr/bin/env bash
# Run nginx as nginx user

chmod ugo+wrx /etc/nginx/nginx.conf
# chmod 644
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkil -l apache2
sudo -u nginx service nginx restart
